### PR TITLE
Correct Cleanup when ScriBt exits

### PR DESCRIPTION
**Pull request by timschumi**
- Always delete temp.txt, temp_v1.txt and temp_v2.txt
 - Delete temp_sync.txt if it's empty
 - Delete temp_compile.txt if it's empty
 - Delete upScriBt.sh if not in ScriBt directory

Linked to Issue (#19)

### CODE REVIEW

**Comment by a7r3** [comment]
@TimSchumi ^^that was a late comment

For upScriBt ops, It first `cd` s to the PATHDIR if it is non zero, else it'd do nothing and execute upScriBt.sh

So no need to curl it to current / PATH directory, it's taken care of

On another note, unless and until upScriBt is seperated from the repo, it cannot be removed, better to keep working directory clean. (EDIT: Oh wait, you said that already :+1: )

**Comment by timschumi** [comment]
Means this could be merged now as-is?

**Comment by a7r3** [comment]
Yes, and it's `staging` so issues could be solved quickly without disturbing the `master` branch

**Comment by timschumi** [comment]
Ready to merge (at least from my side)

**Comment by timschumi** [comment]
I added the last commit because there were errors when exiting from the Kernel Builder. I may have added CALL_ME_ROOT on too many places but better safe than sorry (Restoring the variables works there now, too)

Terminal Output:
`===============[!] Kernel Building [!]=================
Building on : timschumi@buildmachine

...

[!] Unsetting all variables
diff: temp_v1.txt: File or Folder not found

[!] Thanks for using ScriBt.

[<3] Peace! :)

rm: Removing 'temp_v1.txt' failed: File or Folder not found
rm: Removing 'temp.txt' failed: File or Folder not found
rm: Removing 'temp_sync.txt' failed: File or Folder not found
rm: Removing 'temp_compile.txt' failed: File or Folder not found
rm: Removing 'upScriBt.sh' failed: File or Folder not found`

Also, it seems that the Kernel Builder is not successfully switching back to the root dir after running the build, but I will do that in another PR

**Comment by a7r3** [comment]
@TimSchumi that's a good one! :+1: 

I'd look into that issue now... Would let you know.

These three commits would be merged soon :v:

**Comment by a7r3** [comment]
@TimSchumi the issue seems to be resolved now. Would rebase my changes after merging these commits.

**Pull request merged**
